default: &default
  adapter: postgresql
  encoding: utf-8
  pool: 5

development:
  <<: *default
  database: pear-api_development
  user: root
  password:
  host: localhost

test:
  <<: *default
  database: pear-api_test
  user: root
  password:
  host: localhost

production:
  <<: *default
  database: pear-api_production
  username: pear-api
  password: <%= ENV['EXAMIFY-API_DATABASE_PASSWORD'] %>
